openapi: 3.0.3
servers:
  - url: "http://127.0.0.1:9001"
    description: Test/Dev Server
info:
  description: Authentication/Authorization service for bby-buohub.
  version: "0.1.0"
  title: bby-buohub-auth
  contact:
    email: sfey1@my.bcit.ca
  license:
    name: AGPLv3
    url: "https://www.gnu.org/licenses/agpl-3.0.txt"
tags:
  - name: internal
    description: Meant for internal services only.
  - name: external
    description: Allowed to be accessed by external client.
paths:
  /ping:
    get:
      tags:
        - internal
      summary: Is this thing on?
      description: |
        It send back 200 and the text "pong"
      responses:
        "200":
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /stream/{id}/{filename}:
    get:
      summary: serve a static file specified by uuid and filename
      responses:
        "200":
          description: requested file
  /upload:
    post:
      tags:
        - internal
      summary: upload a video file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - uuid
                - file
              properties:
                uuid:
                  type: string
                  format: uuid
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: upload success and queued for processing
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    errorResponse:
      type: object
      required:
        - errorName
        - errorText
      properties:
        errorName:
          type: string
        errorText:
          type: string
