apiVersion: apps/v1
kind: Deployment
metadata:
  name: bby-auth-deploy
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: auth-pod
          image: starshinebit/auth:v1
          env:
            - name: SERVER_ENV
              value: prod
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user-password
            - name: GIN_MODE
              value: release
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /ping
              port: 9000
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /ping
              port: 9000
            failureThreshold: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
